fix

diff --git a/initContainers/dotnetinitcontainer/Dockerfile b/initContainers/dotnetinitcontainer/Dockerfile
--- a/initContainers/dotnetinitcontainer/Dockerfile
+++ b/initContainers/dotnetinitcontainer/Dockerfile
@@ -11,12 +11,14 @@ RUN apk add --no-cache curl jq
 RUN curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url' | while read -r url; do \
   if [[ -n "$url" ]]; then \
     echo "Downloading $url"; \
-    curl -L -o "$(basename "$url")" "$url" || echo "Failed to download $url"; \
+    curl -L -o "$(basename "$url")" "$url" || { echo "Failed to download $url"; exit 1; }; \
+    echo "Downloaded $(basename "$url")"; \
+    tar -xzf "$(basename "$url")" --directory /app/sealights/agent || { echo "Failed to extract $(basename "$url")"; exit 1; }; \
   else \
     echo "No valid URL found"; \
+    exit 1; \
   fi; \
 done
 
-RUN tar -xzf ./sealights-dotnet-agent-alpine-self-contained.tar.gz --directory /app/sealights/agent
 RUN chmod -R 777 /app/sealights
 COPY start-app.sh /app/sealights
