fix

diff --git a/initContainers/dotnetinitcontainer/Dockerfile b/initContainers/dotnetinitcontainer/Dockerfile
--- a/initContainers/dotnetinitcontainer/Dockerfile
+++ b/initContainers/dotnetinitcontainer/Dockerfile
@@ -12,33 +12,24 @@ WORKDIR /app
 RUN mkdir -p ./sealights/logs
 RUN mkdir -p ./sealights/agent
 
-# Verify token permissions
-RUN curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/user
-
-# Fetch and log all asset names and URLs
-RUN curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest \
-    | jq -r '.assets[] | [.name, .browser_download_url] | @tsv' \
-    | tee /tmp/assets.txt
-
-# Download the specific asset
-RUN grep "sealights-dotnet-agent-alpine-self-contained.tar.gz" /tmp/assets.txt | cut -f2 \
+# Download and rename the specific asset
+RUN curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" \
+        https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest \
+    | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url' \
     | while read -r url; do \
         if [ -n "$url" ]; then \
-          echo "Downloading $url"; \
-          curl -L -o "/tmp/sealights-dotnet-agent-alpine-self-contained.tar.gz" "$url" || echo "Failed to download $url"; \
-          if [ $(stat -c%s "/tmp/sealights-dotnet-agent-alpine-self-contained.tar.gz") -gt 100 ]; then \
-            mv "/tmp/sealights-dotnet-agent-alpine-self-contained.tar.gz" "/app/sealights/agent/sealights-dotnet-agent-alpine.tar.gz"; \
-          else \
-            echo "Downloaded file is too small, indicating a possible error."; \
-            echo "Content of the downloaded file:"; \
-            cat /tmp/sealights-dotnet-agent-alpine-self-contained.tar.gz; \
-            exit 1; \
-          fi \
+            echo "Downloading $url"; \
+            curl -L -o "/tmp/$(basename "$url")" "$url" || echo "Failed to download $url"; \
         else \
-          echo "No valid URL found"; \
-          exit 1; \
+            echo "No valid URL found"; \
         fi \
-      done
+    done
+
+# Verify the downloaded files
+RUN ls -l /tmp
+
+# Rename the downloaded .tar.gz file
+RUN mv /tmp/sealights-dotnet-agent-alpine-self-contained.tar.gz /app/sealights/agent/sealights-dotnet-agent-alpine.tar.gz
 
 # List files to verify download
 RUN ls -l /app/sealights/agent
