fix

diff --git a/initContainers/dotnetinitcontainer/Dockerfile b/initContainers/dotnetinitcontainer/Dockerfile
--- a/initContainers/dotnetinitcontainer/Dockerfile
+++ b/initContainers/dotnetinitcontainer/Dockerfile
@@ -9,15 +9,21 @@ RUN mkdir -p ./sealights/agent
 RUN apk add --no-cache curl jq unzip
 
 # Fetch the download URL for the sealights agent and unzip the file
-RUN DOWNLOAD_URL=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url') && \
-    if [[ -n "$DOWNLOAD_URL" ]]; then \
-        echo "Downloading $DOWNLOAD_URL"; \
-        curl -L -o sealights-dotnet-agent-alpine-self-contained.zip "$DOWNLOAD_URL" || echo "Failed to download $DOWNLOAD_URL"; \
+RUN curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url' | while read -r url; do \
+    if [[ -n "$url" ]]; then \
+        echo "Downloading $url"; \
+        filename=$(basename "$url"); \
+        curl -L -o "$filename" "$url" || echo "Failed to download $url"; \
+        if [[ "$filename" == *.zip ]]; then \
+            unzip "$filename" -d /app/sealights/agent; \
+        elif [[ "$filename" == *.tar.gz ]]; then \
+            tar -xzf "$filename" --directory /app/sealights/agent; \
+        fi; \
     else \
         echo "No valid URL found"; \
-    fi
+    fi; \
+done
 
-RUN unzip ./sealights-dotnet-agent-alpine-self-contained.zip -d /app/sealights/agent
 RUN chmod -R 777 /app/sealights
 
 COPY start-app.sh /app/sealights
