fix

diff --git a/initContainers/dotnetinitcontainer/Dockerfile b/initContainers/dotnetinitcontainer/Dockerfile
--- a/initContainers/dotnetinitcontainer/Dockerfile
+++ b/initContainers/dotnetinitcontainer/Dockerfile
@@ -8,12 +8,12 @@ RUN mkdir -p ./sealights/agent
 
 RUN apk add --no-cache curl jq unzip
 
-# Fetch the download URL for the sealights agent and unzip the file
+# Fetch the download URL for the Sealights agent and handle both tar.gz and zip files
 RUN curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url' | while read -r url; do \
     if [[ -n "$url" ]]; then \
         echo "Downloading $url"; \
         filename=$(basename "$url"); \
-        curl -L -o "$filename" "$url" || { echo "Failed to download $url"; exit 1; }; \
+        curl -L -w "%{http_code}" -o "$filename" "$url" | { read status; if [[ "$status" != "200" ]]; then echo "Failed to download $url with status $status"; cat "$filename"; exit 1; fi; } \
         if [[ "$filename" == *.zip ]]; then \
             unzip -t "$filename" && unzip "$filename" -d /app/sealights/agent || { echo "Failed to unzip $filename"; exit 1; }; \
         elif [[ "$filename" == *.tar.gz ]]; then \
