fix

diff --git a/initContainers/dotnetinitcontainer/Dockerfile b/initContainers/dotnetinitcontainer/Dockerfile
--- a/initContainers/dotnetinitcontainer/Dockerfile
+++ b/initContainers/dotnetinitcontainer/Dockerfile
@@ -8,14 +8,14 @@ RUN mkdir -p ./sealights/agent
 
 RUN apk add --no-cache curl jq
 
-# Fetch the download URL for the sealights agent
-RUN DOWNLOAD_URL=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url') && \
-    if [[ -n "$DOWNLOAD_URL" ]]; then \
-        echo "Downloading $DOWNLOAD_URL"; \
-        curl -L -o sealights-dotnet-agent-alpine-self-contained.tar.gz "$DOWNLOAD_URL" || echo "Failed to download $DOWNLOAD_URL"; \
-    else \
-        echo "No valid URL found"; \
-    fi
+RUN curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Sealights/SL.OnPremise.Agents.DotNet/releases/latest | jq -r '.assets[] | select(.name | test("sealights-dotnet-agent-alpine-self-contained.(tar.gz|zip)$")) | .browser_download_url' | while read -r url; do \
+  if [[ -n "$url" ]]; then \
+    echo "Downloading $url"; \
+    curl -L -o "$(basename "$url")" "$url" || echo "Failed to download $url"; \
+  else \
+    echo "No valid URL found"; \
+  fi; \
+done
 
 RUN tar -xzf ./sealights-dotnet-agent-alpine-self-contained.tar.gz --directory /app/sealights/agent
 RUN chmod -R 777 /app/sealights
